name: dbear creative
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0708'
    - '#feffff'
    - '#626456'
    - '#ca851d'
    - '#feba38'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
