name: dbear creative
favicon: null
layout_spectrum: 0.4517597812227905
typography_spectrum: 0.13680411782115698
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7818067672196776
  lightness: 0.8570429852697998
  saturation: 0.9172987614292651
  rhythmicContrast: 0.013679945841431618
purpose: []
