name: dbear creative
favicon: null
layout_spectrum: 0.27817
typography_spectrum: 0.47294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141a1a'
    - '#59636e'
    - '#bfb0aa'
    - '#efe6d9'
    - '#389937'
  brandStrength: 0.875
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
